services:
  - type: web
    name: repose-of-mind-api
    env: node
    region: singapore
    plan: free
    buildCommand: |
      cd backend
      npm install
      npm run build
    startCommand: |
      cd backend
      node dist/server.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 8080
      - key: MONGODB_URI
        sync: false
      - key: JWT_SECRET
        sync: false
      - key: GEMINI_API_KEY
        sync: false
    healthCheckPath: /
    autoDeploy: true 